#!/usr/bin/env python3
"""Regenerate images_data.h from the JPEGs in images/.

Usage: python3 convert_images.py

Reads every .jpg/.jpeg in this folder's images/ subfolder and emits
images_data.h: one PROGMEM byte array per photo plus a TEST_IMAGES[] table
the .ino cycles through.

Each source is checked against what TJpg_Decoder (used by both this sketch
and device/flight_tracker/photo.h) can actually decode: baseline encoding,
<=282x217 (the backend's panel-fit target, backend/server.js). A photo
straight off planespotters.net or a phone camera is almost always
progressive and oversized, so when Pillow is installed (`pip install
pillow`) a source that fails either check is auto resize-to-fit +
re-encoded baseline (quality 88, 4:4:4 — the same encode profile
backend/server.js uses) rather than just rejected. This mirrors backend's
own photo pipeline (fetch -> resize -> baseline JPEG) minus its
PANEL_TONE_GAMMA / PANEL_GREEN_CURVE calibration LUT, which is
deliberately out of scope here (see the .ino's top comment). The
normalized bytes are also saved to images/_normalized/ so you can inspect
exactly what got embedded. Without Pillow, non-conforming sources are
skipped with instructions instead.
"""
import io
import os
import re
import struct
import sys

try:
    from PIL import Image
    HAVE_PIL = True
except ImportError:
    HAVE_PIL = False

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
IMAGES_DIR = os.path.join(SCRIPT_DIR, "images")
NORMALIZED_DIR = os.path.join(IMAGES_DIR, "_normalized")
OUT_PATH = os.path.join(SCRIPT_DIR, "images_data.h")

# Panel target the backend resizes photos to fit inside (backend/server.js).
PANEL_W, PANEL_H = 282, 217

# Same encode profile as backend/server.js's photo pipeline, minus its
# calibration LUT (out of scope for this driver/library fidelity tool).
JPEG_QUALITY = 88

# JPEG SOF markers. 0xC0/0xC1 are baseline-compatible; anything else
# (0xC2 progressive is the common offender from "Save for Web" exporters,
# and from planespotters.net's own thumbnails) TJpg_Decoder cannot decode.
SOF_BASELINE = {0xC0, 0xC1}
SOF_OTHER = {0xC2, 0xC3, 0xC5, 0xC6, 0xC7, 0xC9, 0xCA, 0xCB, 0xCD, 0xCE, 0xCF}
SOF_ALL = SOF_BASELINE | SOF_OTHER

NO_LENGTH_MARKERS = {0xD8, 0xD9, 0x01} | set(range(0xD0, 0xD8))  # SOI/EOI/TEM/RSTn


def read_jpeg_info(data):
    """Return (width, height, sof_marker) from the first SOF segment, or
    raise ValueError if this doesn't look like a JPEG / has no SOF."""
    if len(data) < 4 or data[0] != 0xFF or data[1] != 0xD8:
        raise ValueError("not a JPEG (missing SOI marker)")
    pos = 2
    while pos + 1 < len(data):
        if data[pos] != 0xFF:
            pos += 1
            continue
        marker = data[pos + 1]
        pos += 2
        if marker == 0xFF:
            continue  # fill byte
        if marker in NO_LENGTH_MARKERS:
            continue
        if marker == 0xDA:  # SOS: image data follows, no SOF before this = malformed
            break
        if pos + 1 >= len(data):
            break
        seg_len = struct.unpack(">H", data[pos:pos + 2])[0]
        if marker in SOF_ALL:
            if pos + 2 + 5 > len(data):
                raise ValueError("truncated SOF segment")
            height = struct.unpack(">H", data[pos + 3:pos + 5])[0]
            width = struct.unpack(">H", data[pos + 5:pos + 7])[0]
            return width, height, marker
        pos += seg_len
    raise ValueError("no SOF marker found (truncated or not a real JPEG)")


def normalize_image(data, fit_w, fit_h):
    """Resize-to-fit (preserving aspect ratio) + re-encode as baseline JPEG,
    matching backend/server.js's fit-inside + baseline-JPEG profile. Returns
    the new JPEG bytes. Requires Pillow (checked by the caller)."""
    img = Image.open(io.BytesIO(data))
    img = img.convert("RGB")  # drop alpha/CMYK — the panel path is RGB565 only
    img.thumbnail((fit_w, fit_h), Image.LANCZOS)  # in-place fit-inside, aspect preserved
    out = io.BytesIO()
    img.save(out, format="JPEG", quality=JPEG_QUALITY, subsampling=0, progressive=False)
    return out.getvalue()


def sanitize_ident(name, idx):
    base = re.sub(r"[^A-Za-z0-9_]", "_", os.path.splitext(name)[0])
    if not base or base[0].isdigit():
        base = "img_" + base
    return f"{base}_{idx}"


def emit_array(f, ident, data):
    f.write(f"const uint8_t {ident}[] PROGMEM = {{\n")
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        f.write("  " + ", ".join(f"0x{b:02X}" for b in chunk) + ",\n")
    f.write("};\n\n")


def main():
    os.makedirs(IMAGES_DIR, exist_ok=True)
    files = sorted(
        fn for fn in os.listdir(IMAGES_DIR)
        if fn.lower().endswith((".jpg", ".jpeg"))
    )

    entries = []  # (ident, filename, len, w, h)

    with open(OUT_PATH, "w") as f:
        f.write("// AUTO-GENERATED by convert_images.py — do not edit by hand.\n")
        f.write("// Regenerate after changing images/: python3 convert_images.py\n")
        f.write("#pragma once\n#include <Arduino.h>\n\n")
        f.write("struct TestImage { const char* name; const uint8_t* data; size_t len; uint16_t w; uint16_t h; };\n\n")

        if not files:
            print(f"No .jpg/.jpeg files found in {IMAGES_DIR}/ — writing an empty table.")
            print("Drop plane-spotter photos in there and re-run this script.")
            f.write("const TestImage TEST_IMAGES[1] = { {\"(none)\", nullptr, 0, 0, 0} };\n")
            f.write("const int TEST_IMAGE_COUNT = 0;\n")
            return

        for idx, fn in enumerate(files):
            path = os.path.join(IMAGES_DIR, fn)
            with open(path, "rb") as imgf:
                data = imgf.read()

            try:
                w, h, sof = read_jpeg_info(data)
            except ValueError as e:
                print(f"SKIP {fn}: {e}")
                continue

            needs_fix = sof in SOF_OTHER or w > PANEL_W or h > PANEL_H
            if needs_fix:
                reason = []
                if sof in SOF_OTHER:
                    reason.append(f"progressive (SOF 0x{sof:02X})")
                if w > PANEL_W or h > PANEL_H:
                    reason.append(f"{w}x{h} exceeds {PANEL_W}x{PANEL_H}")
                reason = ", ".join(reason)

                if not HAVE_PIL:
                    print(f"SKIP {fn}: {reason}. Install Pillow (`pip install pillow`) for "
                          f"auto resize+baseline re-encode, or fix it yourself "
                          f"(e.g. `convert {fn} -resize {PANEL_W}x{PANEL_H} -interlace none out.jpg`) and retry.")
                    continue

                try:
                    data = normalize_image(data, PANEL_W, PANEL_H)
                except Exception as e:
                    print(f"SKIP {fn}: normalize failed ({e})")
                    continue
                w, h, sof = read_jpeg_info(data)
                os.makedirs(NORMALIZED_DIR, exist_ok=True)
                norm_path = os.path.join(NORMALIZED_DIR, os.path.splitext(fn)[0] + ".jpg")
                with open(norm_path, "wb") as nf:
                    nf.write(data)
                print(f"NORMALIZED {fn}: {reason} -> {w}x{h} baseline "
                      f"(saved to images/_normalized/{os.path.basename(norm_path)})")

            ident = sanitize_ident(fn, idx)
            emit_array(f, ident, data)
            entries.append((ident, fn, len(data), w, h))

        f.write("const TestImage TEST_IMAGES[] = {\n")
        for ident, fn, length, w, h in entries:
            f.write(f'  {{ "{fn}", {ident}, {length}, {w}, {h} }},\n')
        f.write("};\n")
        f.write(f"const int TEST_IMAGE_COUNT = {len(entries)};\n")

    print(f"Wrote {OUT_PATH}: {len(entries)} image(s).")
    if not entries:
        print("All candidate files were skipped — see SKIP lines above. images_data.h has an empty table.")


if __name__ == "__main__":
    sys.exit(main())
